name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.arvind09112004 }}
        password: ${{ secrets.Arvi@1234 }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: arvind09112004/my-node-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.13.60.58.200 }}
        USER: ec2-user
        KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$KEY" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << 'EOF'
          docker pull arvind09112004/my-node-app:latest
          docker stop my-node-app || true
          docker rm my-node-app || true
          docker run -d --name my-node-app -p 80:80 arvind09112004/my-node-app:latest
        EOF
